### ISSUE TITLE
Relate text on Subject to ScopedAffiliations 

### ISSUE THREAD

**Issue by nicoleharris** [leifj/academia-category#11]
Specifically a relying party SHOULD NOT assume that an attribute assertion received from an identity provider with the academia entity category represents a Subject (as defined in [SAMLCore]) with any particular affiliation to the organization on behalf of which the identity provider is operated. Conversely, the absense of the academia category does not mean that the identity provider does not in fact represent one or more academic institution.  Submitted by Eric Goodman to the REFEDS consultation

**Comment by leifj** [comment]
So this issue would seem to clash with #14 right?

**Comment by nicoleharris** [comment]
Have added some text to the revised refeds version.
