### ISSUE TITLE
Small text change

### ISSUE THREAD

**Issue by nicoleharris** [leifj/academia-category#13]
Change text as shown: 

An identity provider MUST NOT be annotated with the academia entity category unless it is being operated

```
by or

on behalf of and by contract with at least one organisation represented by a legal entity in good standing in the community of other academic institutions **THAT** fulfills at least one of the criteria below:
```

**Comment by nicoleharris** [comment]
Further comment on this:

"by" is unnecessary and could bring in some user organisations that you don't intend. "By" would include an IdP operated by a university as a (pay-for) service to non-educational organisations. "On behalf of" covers in-house IdPs anyway. For IdPs operated by someone else, I'd suggest "by contract or other written agreement", rather than specifying a particular form of that agreement. Indeed it may be that "on behalf of" covers that situation as well, in which case all you need is "on behalf of an organisation represented by a legal entity in good standing ... (etc)"?

**Comment by alanbuxey** [comment]
the 'operated by' is a red herring - it could be managed, SaaS, IaaS (if it's in AWS/Azure then amazon/microsoft are part of the operation.  the key aspect is that the IdP is authenticating users who are at an organisation that is eligible/ in good standing  ?

**Comment by nicoleharris** [comment]
I changed operated to manage and added the written agreement suggestion in the refeds fork
