### ISSUE TITLE
Change from "academic" to "trusted to assert academic status of users"?

### ISSUE THREAD

**Issue by nicoleharris** [leifj/academia-category#14]
"Research and Education Federations are encouraged to use the REFEDS Academia Entity Category to annotate those member identity providers that represent academic institutions."

Scope the category not to be "are you academic?", but "should you be trusted to assert academically-oriented data about users"?

**Comment by nicoleharris** [comment]
An identity provider annotated with the academia category implies that the registrar has made the determination that the identity provider SHOULD be trusted to assert the following attributes [...]. When making the decision to annotate an identity provider with the academia category a registry SHOULD consider the following criteria: [...]

**Comment by alanbuxey** [comment]
...would this assertion go hand in hand that affiliation MUST be released - the relying party cannot assume that all authentications from such entity-tagged organisations are from valid academic-related members (staff/student/whatever) - a lot of these sites have day visitors with guest accounts for example..

**Comment by leifj** [comment]
I like this idea a lot. PR so we can discuss specific text?

**Comment by nicoleharris** [comment]
have had an attempt at wording this in the revised refeds version

**Comment by nicoleharris** [comment]
This issue can now be closed
