### ISSUE TITLE
Definition for 'teaching hospital' specific enough?

### ISSUE THREAD

**Issue by thlengge** [leifj/academia-category#17]
Is 'teaching hospital' well enough defied?

[Wikipedia](https://en.wikipedia.org/wiki/Teaching_hospital) says: 'A teaching hospital is a hospital or medical center that provides clinical education and training to future and current health professionals'

Do we need to restrict that to health professionals who aim for a degree at level 6 (or higher) according to [ISCED 2011](http://uis.unesco.org/en/isced-mappings) in analogy to 1)? 
Or do we also want to include hospitals that 'only' train health professionals who aim for a degree at level 3 or 4?

**Comment by leifj** [comment]
mixed up #17 and #18 in that commit

**Comment by alanbuxey** [comment]
definition of teaching hospital varies by region/country - the question is what is suitable/expected by the service providers/journal/publication partners etc?

**Comment by thlengge** [comment]
When we already know something lacks a clear definition and gets interpreted differently, we better try to limit the spectrum for interpretation from the beginning.

In analogy to
> 1. the organization is dedicated to education and research and which grants academic degrees at level 6 (or higher) according to ISCED 2011 [ISCED] or equivalent internationally recognized academic degree levels.

I am in favour of being as restrictive as in 1.

It could then make sense to move teaching hospitals upwards to position 2.

**Comment by nicoleharris** [comment]
I've added this proposal to the refeds forked version
