### ISSUE TITLE
A question regarding the nature of "Academic Institutions"

### ISSUE THREAD

**Issue by nckroy** [leifj/academia-category#7]
The overview section says this category is intended to:

"...annotate those member identity providers that represent academic institutions, in order to distinguish them from identity providers that are not able to claim any affiliation with the international research and education community."

However, the definition section sets the bar for degree-granting institutions at ISCED level 6.  There are a number of level 5 degree-granting institutions in the US ("community colleges") that have faculty that contribute to national and international research projects, and may be funded by agencies such as the NSF.  I'm concerned that the cut-off at level 6 may cause IdPs with participants in international research to be hidden from discovery.

**Comment by nckroy** [comment]
The other gap I see is section 2.5 - in the US, accrediting bodies that determine the validity of academic institutions are non-government organizations.

**Comment by alanbuxey** [comment]
perhaps a requirement for 'research institute' to denote an institute that participates in such funded  research - this would be an entity that could be alongside the other entities
