### ISSUE TITLE
Academia category can be assigned to arbitrary 'Guest' or IDP of last resort status which have noticeably less stringent practices

### ISSUE THREAD

**Issue by canariecaf** [leifj/academia-category#9]
I know of one, maybe two use cases where the definition in 2, section 2 permits IdPs that allow accounts to be created arbitrarily, much like a guest IdP, to be tagged with this category when I think it should not be.

To permit the tag to be issued, I propose that an  IdP MUST pass muster on the follow questions:
- is this IdP able to assert identity of equal calibre as the other IdPs in the federation?
- are the policies that such an IdP of sufficiently equal to support the assessment of the aforementioned question? (e.g. does said IdP do sufficient identity proofing?)

Institutions are the underwriters of the identities that they mint. At the end of the day they are ultimately accountable to the behaviour and discipline(if required) on the account.   If there is something OTHER than an institution minting identities, how can they be assigned the academia category if they do not have the same strength and relationship to the accountability of the accounts they mint?

I would recommend some additional criteria to back the academia category to reflect this.

**Comment by canariecaf** [comment]
Additionally:

If one assesses an institutional IdM 'infrastructure' (aka it's
implementation, policy, and operational practices and behaviour) and any
VO's IdM 'infrastructure' I think one would find the scales rarely balance
out as one would want them to.  If that is the case, then are they equally
entitled to have their entity tagged with the Academia category?

One outcome (to be avoided) is that if there is no confidence in the
accuracy in assigning of the category Federation Operators are going to
start manipulating [eduGAIN] aggregates at an entity level removing
categories to avoid ingesting 'things we don't trust'.  This obviously has
scaling challenges and to me is a step backwards if we can't find a good
balance on the definition and how to evaluate it's assignment criteria.

**Comment by canariecaf** [comment]
Addendum 2:
The balance scale can tip in both directions(to either the institution OR VO) when examining IdPs.

At times it may be that a VO's IdM 'infrastructure' is more precise than an institutions one. 
Their focus is  more narrowly aimed on access and authorization for THAT purpose and not a generic purpose as an Institution may be charged with doing for their central IdM infrastructure.

The question then turns to 'is the organization as equipped, capable  and more importantly OBLIGATED to do things a certain way?

At the end of the day, if 'something goes bump in the night' who is left holding the bag?
In the case of research projects, is that the 'project' holding the bag or is it the institution that is the home for the project?

These are elements to consider in the assignment of the category or to be written into the definition itself because the community will use the 'Academia' tag as an instrument to bulk handle all those tagged with it as being 'sufficiently' equal to possess it.

**Comment by leifj** [comment]
related to #14 ?

**Comment by nicoleharris** [comment]
Make this part of the registration criteria section?  I think this is mostly covered by the requirement "good standing in the community of other academic institutions".  Otherwise beginning to slip down the rabbit hole of assurance.

**Comment by canariecaf** [comment]
After reviewing the current version, I'm ok to close this. I think this is captured in what @nicoleharris refers to and think the text is better than it was from Aug 2015. Note that I opened 2 pull requests on different items than this.  The pull requests are to @leifj version not REFEDS.  I welcome discussion on it but if it's better to place the pull requests against REFEDS' version, I'll do that.
